// Copyright 2026 syzkaller project authors. All rights reserved.
// Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

package csource

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"

	"github.com/google/syzkaller/prog"
)

// csbDialect adapts a normal syzkaller C reproducer for inclusion as one of
// several independently namespaced benchmark headers in a CSB translation unit.
type csbDialect struct {
	ctx *context
}

func (dialect *csbDialect) sandboxCall(name string, arg int) string {
	if name == "" {
		return "LOOPUNIQUE(ctx, op_id);"
	}
	args := []string{}
	if name == "android" {
		args = append(args, strconv.Itoa(arg))
	}
	args = append(args, "ctx")
	return "do_sandbox_" + name + "(" + strings.Join(args, ",") + ");"
}

func (dialect *csbDialect) sourceHeader() (string, string, error) {
	ctx := dialect.ctx
	header := "// autogenerated by syzkaller (https://github.com/google/syzkaller)\n" +
		"// clang-format off\n" +
		"#ifndef UNIQUE_ID\n#define UNIQUE_ID\n#endif\n" +
		"#define RESOLVE(x) x\n" +
		"#define BM_JOIN(a,b) a ## b\n" +
		"#define BM_CAT(a,b) BM_JOIN(a,b)\n" +
		"#define UNIQUE_ID_TOK_TOK(...) BM_CAT(__VA_OPT__(_),RESOLVE(UNIQUE_ID))\n" +
		"#define UNIQUE_ID_TOK RESOLVE(UNIQUE_ID_TOK_TOK(RESOLVE(UNIQUE_ID)))\n" +
		"#define UNIQUE_NAME(prefix, tok) BM_CAT(prefix,tok)\n" +
		"#define UNIQUE_VAR(var) UNIQUE_NAME(var, RESOLVE(UNIQUE_ID_TOK))\n" +
		"#define UNIQUE_FUNC(func) UNIQUE_NAME(func, RESOLVE(UNIQUE_ID_TOK))\n" +
		"#define UNIQUE_GOTO(mark) UNIQUE_NAME(mark, RESOLVE(UNIQUE_ID_TOK))\n" +
		"#define UNIQUE_STR_STR(str) #str\n" +
		"#define UNIQUE_STR() UNIQUE_STR_STR(RESOLVE(UNIQUE_ID))\n" +
		fmt.Sprintf("#define MMAP_OFFSET 0x%xul\n", ctx.target.DataOffset) +
		fmt.Sprintf("#define MMAP_LENGTH 0x%xul\n", ctx.target.NumPages*ctx.target.PageSize) +
		fmt.Sprintf("const static uint64_t UNIQUE_VAR(maxWriteBufferSize) = %dul;\n", ctx.opts.MaxWriteSize) +
		fmt.Sprintf("const static uint64_t UNIQUE_VAR(maxWriteBufferSizeAlignment) = %dul;\n", ctx.opts.MaxWriteSizeAlignment)
	metadata := ""
	connect, err := toStringArray(NetOpsFDsConnect)
	if err != nil {
		return "", "", err
	}
	header += fmt.Sprintf("const char* UNIQUE_VAR(netops_connect)[%d] = {%s};\n", len(NetOpsFDsConnect), connect)
	if connect != "" {
		metadata += fmt.Sprintf("CLIENT_SEQ=%s\n", connect)
	}
	accept, err := toStringArray(NetOpsFDsAccept)
	if err != nil {
		return "", "", err
	}
	header += fmt.Sprintf("const char* UNIQUE_VAR(netops_accept)[%d] = {%s};\n", len(NetOpsFDsAccept), accept)
	if accept != "" {
		metadata += fmt.Sprintf("SERVER_SEQ=%s\n", accept)
	}
	return header + "\n", metadata, nil
}

func (*csbDialect) traceEpilogue(w *bytes.Buffer, _ int, _ string) {
	fmt.Fprintln(w, "\tif (res == -1) { assert(!abort_on_fail); UNIQUE_VAR(ctx->num_failed)++; } else { UNIQUE_VAR(ctx->num_succeeded)++; }")
}

func (*csbDialect) pseudoCallName(name string) string {
	// CSB-only helpers are header-local because several generated benchmarks
	// share one translation unit. Affinity replay follows the same contract.
	if strings.HasPrefix(name, "syz_csb_") || name == "syz_reapply_affinity" {
		return fmt.Sprintf("UNIQUE_FUNC(%v)", name)
	}
	return name
}

func (*csbDialect) rewriteArgument(call prog.ExecCall, callName string, index int) (string, bool) {
	if index == 0 {
		switch callName {
		case "readlinkat", "openat", "faccessat", "faccessat2", "newfstatat", "unlinkat", "mknodat", "fchownat", "fchmodat":
			return "UNIQUE_VAR(ctx->dirfd)", true
		}
	}
	if index == 1 {
		switch call.Meta.Name {
		case "connect$inet":
			return "UNIQUE_VAR(ctx->connect4_arg)", true
		case "bind$inet":
			return "UNIQUE_VAR(ctx->bind4_arg)", true
		case "connect$inet6":
			return "UNIQUE_VAR(ctx->connect6_arg)", true
		case "bind$inet6":
			return "UNIQUE_VAR(ctx->bind6_arg)", true
		}
		switch callName {
		case "write", "pwrite64", "send", "sendto":
			return "UNIQUE_VAR(ctx->writeBuffer)", true
		}
	}
	if index == 2 {
		switch call.Meta.Name {
		case "connect$inet":
			return "sizeof(*(UNIQUE_VAR(ctx->connect4_arg)))", true
		case "bind$inet":
			return "sizeof(*(UNIQUE_VAR(ctx->bind4_arg)))", true
		case "connect$inet6":
			return "sizeof(*(UNIQUE_VAR(ctx->connect6_arg)))", true
		case "bind$inet6":
			return "sizeof(*(UNIQUE_VAR(ctx->bind6_arg)))", true
		case "bind$unix":
			return "sizeof(sa_family_t)", true
		}
	}
	return "", false
}

func (dialect *csbDialect) pointerOffset(value uint64) string {
	min := dialect.ctx.sysTarget.DataOffset
	max := min + dialect.ctx.target.NumPages*dialect.ctx.target.PageSize
	if value >= min && value < max {
		return "+PTR_OFFSET"
	}
	return ""
}

func (*csbDialect) resultArrayName() string {
	return "UNIQUE_VAR(ctx->r)"
}

func (*csbDialect) rewriteExit(result []byte) []byte {
	return bytes.ReplaceAll(result, []byte("UNIQUE_FUNC(doexit)("), []byte("exit("))
}

func (*csbDialect) emitProgramBanner(*bytes.Buffer, bool) {
}

func (*csbDialect) emitUnusedResult(w *bytes.Buffer) {
	fmt.Fprintln(w, "\tV_UNUSED(res);")
}

func (*csbDialect) declareResults([]uint64) string {
	return ""
}

func (*csbDialect) assembleCalls(_ string, syscalls, declarations, closes string) (string, string) {
	return "", declarations + "\n" + syscalls + "\n" + closes
}
