// Copyright 2026 syzkaller project authors. All rights reserved.
// Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.

package csource

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"

	"github.com/google/syzkaller/prog"
)

// csbDialect adapts a normal syzkaller C reproducer for compilation as a
// private CSB program translation unit.
type csbDialect struct {
	ctx *context
}

func (dialect *csbDialect) sandboxCall(name string, arg int) string {
	if name == "" {
		return "loop(ctx, op_id);"
	}
	args := []string{}
	if name == "android" {
		args = append(args, strconv.Itoa(arg))
	}
	args = append(args, "ctx")
	return "do_sandbox_" + name + "(" + strings.Join(args, ",") + ");"
}

func (dialect *csbDialect) sourceHeader() (string, string, error) {
	ctx := dialect.ctx
	header := "// autogenerated by syzkaller (https://github.com/google/syzkaller)\n" +
		"// clang-format off\n" +
		"#ifndef CSB_PROGRAM_NAME\n#define CSB_PROGRAM_NAME \"\"\n#endif\n" +
		fmt.Sprintf("#define MMAP_OFFSET 0x%xul\n", ctx.target.DataOffset) +
		fmt.Sprintf("#define MMAP_LENGTH 0x%xul\n", ctx.target.NumPages*ctx.target.PageSize) +
		fmt.Sprintf("const static uint64_t maxWriteBufferSize = %dul;\n", ctx.opts.MaxWriteSize) +
		fmt.Sprintf("const static uint64_t maxWriteBufferSizeAlignment = %dul;\n", ctx.opts.MaxWriteSizeAlignment)
	metadata := ""
	connect, err := toStringArray(NetOpsFDsConnect)
	if err != nil {
		return "", "", err
	}
	header += fmt.Sprintf("static const char* netops_connect[%d] __attribute__((unused)) = {%s};\n", len(NetOpsFDsConnect), connect)
	if connect != "" {
		metadata += fmt.Sprintf("CLIENT_SEQ=%s\n", connect)
	}
	accept, err := toStringArray(NetOpsFDsAccept)
	if err != nil {
		return "", "", err
	}
	header += fmt.Sprintf("static const char* netops_accept[%d] __attribute__((unused)) = {%s};\n", len(NetOpsFDsAccept), accept)
	if accept != "" {
		metadata += fmt.Sprintf("SERVER_SEQ=%s\n", accept)
	}
	return header + "\n", metadata, nil
}

func (*csbDialect) traceEpilogue(w *bytes.Buffer, _ int, _ string) {
	fmt.Fprintln(w, "\tif (res == -1 ) { assert(!abort_on_fail); ctx->num_failed++;} else {ctx->num_succeeded++;};")
}

func (*csbDialect) pseudoCallName(name string) string {
	return name
}

func (*csbDialect) rewriteArgument(call prog.ExecCall, callName string, index int) (string, bool) {
	if index == 0 {
		switch callName {
		case "readlinkat", "openat", "faccessat", "faccessat2", "newfstatat", "unlinkat", "mknodat", "fchownat", "fchmodat":
			return "ctx->dirfd", true
		}
	}
	if index == 1 {
		switch call.Meta.Name {
		case "connect$inet":
			return "ctx->connect4_arg", true
		case "bind$inet":
			return "ctx->bind4_arg", true
		case "connect$inet6":
			return "ctx->connect6_arg", true
		case "bind$inet6":
			return "ctx->bind6_arg", true
		}
		switch callName {
		case "write", "pwrite64", "send", "sendto":
			return "ctx->writeBuffer", true
		}
	}
	if index == 2 {
		switch call.Meta.Name {
		case "connect$inet":
			return "sizeof(*(ctx->connect4_arg))", true
		case "bind$inet":
			return "sizeof(*(ctx->bind4_arg))", true
		case "connect$inet6":
			return "sizeof(*(ctx->connect6_arg))", true
		case "bind$inet6":
			return "sizeof(*(ctx->bind6_arg))", true
		case "bind$unix":
			return "sizeof(sa_family_t)", true
		}
	}
	return "", false
}

func (dialect *csbDialect) pointerOffset(value uint64) string {
	min := dialect.ctx.sysTarget.DataOffset
	max := min + dialect.ctx.target.NumPages*dialect.ctx.target.PageSize
	if value >= min && value < max {
		return "+PTR_OFFSET"
	}
	return ""
}

func (*csbDialect) resultArrayName() string {
	return "ctx->r"
}

func (*csbDialect) rewriteExit(result []byte) []byte {
	return bytes.ReplaceAll(result, []byte("doexit("), []byte("exit("))
}

func (*csbDialect) emitProgramBanner(*bytes.Buffer, bool) {
}

func (*csbDialect) emitUnusedResult(w *bytes.Buffer) {
	fmt.Fprintln(w, "\tV_UNUSED(res);")
}

func (*csbDialect) declareResults([]uint64) string {
	return ""
}

func (*csbDialect) assembleCalls(_ string, syscalls, declarations, closes string) (string, string) {
	return "", declarations + "\n" + syscalls + "\n" + closes
}
